"""update table user

Revision ID: 883c260c122d
Revises: 662dbf4480fa
Create Date: 2024-03-25 12:53:05.297769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883c260c122d'
down_revision = '662dbf4480fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.BigInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
